person:
  name: qinweizhao
  age: 24
  birth: 1997/12/01
  email: 11111
  pet:
      tom:
        name: 小狗
  friend:
    - one
    - two




# 随机数

#  ${random.value}、${random.int}、${random.long}
#  ${random.int(10)}、${random.int[1024,65536]}



#person:
#  name: qinweizhao ${random.uuid}
#  age: ${random.int}
#  birth: 1997/12/01
#  #  email: 11111
#  pet:
#    tom:
#      name: ${person.hello:hello}小狗
#  friend:
#    - one
#    - two