elasticjob:
  reg-center:
    server-lists: 127.0.0.1:2181
    namespace: elasticjob-lite-springboot
  jobs:
    dataflowJob:
      elasticJobClass: org.apache.shardingsphere.elasticjob.dataflow.job.DataflowJob
      cron: 0/5 * * * * ?
      shardingTotalCount: 3
      shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
#    scriptJob:
#      elasticJobType: SCRIPT
#      cron: 0/10 * * * * ?
#      shardingTotalCount: 3
#      props:
#    script.command.line: "echo SCRIPT Job: "

logging:
  level:
    root: debug