elasticjob:
  reg-center:
    server-lists: 127.0.0.1:2181
    namespace: springboot-elasticjob-lite
  jobs:
    simpleJob:
      elastic-job-class: com.qinweizhao.elasticjob.lite.job.MySimpleJob
      cron: 0/10 * * * * ?
      shardingTotalCount: 3
      shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
    dataflowJob:
      elasticJobClass: com.qinweizhao.elasticjob.lite.job.MyDataflowJob
      cron: 0/10 * * * * ?
      shardingTotalCount: 3
      shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
    scriptJob:
      elasticJobType: SCRIPT
      cron: 0/10 * * * * ?
      shardingTotalCount: 3
      props:
        script.command.line: "java -version"

logging:
  level:
    root: info