server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: oauth2-gateway
  cloud:
    nacos:
      ## \u6CE8\u518C\u4E2D\u5FC3\u914D\u7F6E
      discovery:
        # nacos\u7684\u670D\u52A1\u5730\u5740\uFF0Cnacos-server\u4E2DIP\u5730\u5740:\u7AEF\u53E3\u53F7
        server-addr: 127.0.0.1:8848
    gateway:
      ## \u8DEF\u7531
      routes:
        ## id\u53EA\u8981\u552F\u4E00\u5373\u53EF\uFF0C\u540D\u79F0\u4EFB\u610F
        - id: oauth2-auth
          uri: lb://oauth2-auth
          predicates:
            ## Path Route Predicate Factory\u65AD\u8A00
            - Path=/oauth/**
        - id: oauth2-resource
          uri: lb://oauth2-resource
          predicates:
            ## Path Route Predicate Factory\u65AD\u8A00
            - Path=/order/**
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 15000
oauth2:
  cloud:
    sys:
      parameter:
        ignoreUrls:
          - /oauth/token
          - /oauth/authorize

